spring:
  application:
    name: rent-service
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASEURL}
  cloud:
    inetutils:
      ignored-interfaces:
        - vbox*
        - bridge*
        - awd*
        - lo*
        - gif*
        - stf*
        - en1
        - en2
    consul:
      discovery:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  rabbitmq:
    host: ${rabbitmq.host}

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

logging:
  level.org.springframework.cloud: ERROR
